#!/bin/bash

# Setup script for GitHub Secrets
# This script helps you configure the required secrets for automatic Vercel deployment

echo "=================================="
echo "GitHub Secrets Setup for Vercel"
echo "=================================="
echo ""
echo "This script will guide you through setting up the required GitHub secrets."
echo ""
echo "You need to manually add these secrets to your GitHub repository:"
echo ""
echo "1. VERCEL_TOKEN"
echo "2. VERCEL_ORG_ID"
echo "3. VERCEL_PROJECT_ID"
echo ""
echo "Step 1: Create a Vercel Token"
echo "------------------------------"
echo "1. Go to: https://vercel.com/account/tokens"
echo "2. Click 'Create Token'"
echo "3. Give it a name (e.g., 'GitHub Actions - mantine-select-async-paginate')"
echo "4. Copy the token (you won't be able to see it again!)"
echo ""
read -p "Press Enter when you have copied your Vercel token..."

echo ""
echo "Step 2: Add Secrets to GitHub"
echo "------------------------------"
echo "Go to: https://github.com/heytulsiprasad/mantine-select-async-paginate/settings/secrets/actions"
echo ""
echo "Click 'New repository secret' for each of these:"
echo ""
echo "Secret 1:"
echo "  Name: VERCEL_TOKEN"
echo "  Value: [Paste the token you just created]"
echo ""
echo "Secret 2:"
echo "  Name: VERCEL_ORG_ID"
echo "  Value: team_UF4kXugIfOo52wyiHsd3bElI"
echo ""
echo "Secret 3:"
echo "  Name: VERCEL_PROJECT_ID"
echo "  Value: prj_MNlGEMAu2Aws6CSbOmN0VgLYL5U5"
echo ""
read -p "Press Enter when you have added all three secrets..."

echo ""
echo "Step 3: Test the Deployment"
echo "---------------------------"
echo "You can test the automatic deployment by:"
echo "1. Making a small change to any file"
echo "2. Committing and pushing to main branch"
echo "3. Check the Actions tab on GitHub to see the deployment progress"
echo ""
echo "Your deployment workflow is now configured!"
echo ""
echo "Current Vercel deployment URL:"
echo "https://mantine-select-async-paginate-tulsi-prasads-projects.vercel.app/"
echo ""
echo "=================================="
echo "Setup Complete!"
echo "=================================="